# Generated by Django 4.2.7 on 2024-04-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.BigIntegerField(null=True, verbose_name='Telegram chat ID'),
        ),
    ]
