# Generated by Django 4.2.7 on 2024-04-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.CharField(max_length=100, null=True, verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(max_length=64, null=True, verbose_name='место'),
        ),
    ]
